# Generated by Django 5.1.1 on 2025-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='news_articl_title_dca5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content'], name='news_articl_content_c4b88d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='news_articl_publish_90ca8c_idx'),
        ),
    ]
